# Utilisation du SDK pour la construction
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ./src/api2/api2.csproj ./api2/
RUN dotnet restore api2/api2.csproj

COPY ./src/api2/ ./api2/
WORKDIR /src/api2
RUN dotnet publish -c Release -o /app

# Utilisation de l'image runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "api2.dll"]
